// ActionHandler2.java
// Used for handling events generated by List (playlist) items.

package mp3;

import java.awt.event.*;

// ###########################################################################
class ActionHandler2 implements ActionListener {

    Player2 plr;
    PlaySong plSng;

    public ActionHandler2(Player2 plr) {
        this.plr = plr;
    }

    public void actionPerformed(ActionEvent ae) {
        // Get the complete name and path of song using the action command of
        // List item that generated this event.
        plr.curSng = plr.dir + ae.getActionCommand();

        // Set the current Song no. using the Index of Playlist.
        plr.sngNo = plr.plList.getSelectedIndex();

        plSng = new PlaySong(plr);
        plSng.startPlay();  // Now start the decoder.

        // Display Current Song name and current PlayRate
        plr.display.setText(ae.getActionCommand());
        plr.rateDisplay.setText(("  PlayRate: " + plr.player.getRate()));
    }
}